### ISSUE TITLE
bias_diff_off slider seems not to update

### ISSUE THREAD

**Issue by FriedhelmHamann** [tub-rip/CoCapture#35]
There seems to be a mismatch between the selected slider position for 'bias_diff_off' in ImGui and in the camera. The sliders for the other bias values work fine

**Comment by filbert14** [comment]
How much of a mismatch? Could you adjust the slider value for "bias_diff_off" and post a screenshot containing the modified slider and the debug panel? 

Also, try adjusting the "bias_diff_off" slider to a certain value and just try recording somewhere. Metavision SDK spits out a file containing the bias values used for the "output.raw" recording file, so it should contain the most "accurate" bias values - might help to be able to see what's actually going on in there

Does it happen too with another camera? Another thing to add - a setting from the event signal processing panel (can't recall what ATM) also suffers from this exact issue, which is why I placed a debug panel there :))
